### ISSUE TITLE
Macro type: filename not works

### ISSUE THREAD

**Issue by openingnow** [AkiraMiyakoda/cppIncludeGuard#3]
After setting Macro type as filename, extension doesn't makes valid macro.

```cpp
#ifndef 
#define 

// contents

#endif /*  */

```

After some crude debugging, I found `baseUri` is `undefined`.
<img width="765" alt="Screen Shot 2020-02-07 at 7 27 03 PM" src="https://user-images.githubusercontent.com/13010420/74022241-743edc00-49e0-11ea-96b1-f45c39007ca1.png">

Not sure why this happens. Maybe OS incompatibility?

my environment:
```yaml
Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:33.119Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0
```
